select * from customer limit 5;

--Q1.What is the total revenue generated by male vs female customers?
select "Gender", SUM("Purchase Amount (USD)") as revenue
from customer
group by "Gender";

--Q2. Which customers used a discount but still spent more than the avergae purchase amount?
select "Customer ID", "Purchase Amount (USD)"
from customer
where "Discount Applied"='Yes' and "Purchase Amount (USD)">=(select AVG("Purchase Amount (USD)")from customer)

--Q3 Which are the top 5 products with highest average review rating?
select "Item Purchased" , ROUND(AVG("Review Rating::numeric"),2) as "Average product rating"
from customer
group by "Item Purchased"
order by avg("Review Rating") desc
limit 5;

--Q4 Compare the average purchase amount between standard and express shipping
select "Shipping Type",
ROUND(AVG("Purchase Amount (USD)"),2)
from customer
where "Shipping Type" in ('Standard', 'Express')
group by "Shipping Type"

--Q5 Do subscribes customer spend more? Compare Average spend and total revenue between subscribers and non subscribers.
select "Subscription Status",
COUNT("Customer ID") as total_customers,
ROUND(AVG("Purchase Amount (USD)"),2) as avg_spend,
ROUND(SUM("Purchase Amount (USD)"),2) as total_revenue
from customer
group by "Subscription Status"
order by total_revenue, avg_spend desc;

--Q6 Which 5 products have the highestpercentage of purchases with discounts applied?
select "Item Purchased",
ROUND(100 * SUM(CASE WHEN "Discount Applied"='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by "Item Purchased"
order by discount_rate desc
limit 5;

--Q7 Segment customers into NEw, Returning and loyal
--based on the total no. of previous purchases and show the count of each segment.
with customer_type as (
select "Customer ID","Previous Purchases",
CASE WHEN"Previous Purchases"=1 THEN 'NEW' 
     WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
     ELSE 'Loyal'
     END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment